print("andria patsatsia")
print()
print("the ant and dove")
print()
print("   One hot day, an ant was searching for some water.")
print("Afrer walking around for some time, she came to a spring.")
print("To reach the spring, she had to climb up a blade of grass.")
print("while making her way up, she slippedand fell into water.")
print("   She could have drowned if dove up a nearby tree have not seen her.")
print("Seeing that the ant was in trouble,")
print("the dove quickly picked off a leaf and dropped it into the water near the an.")
print("The ant moved towards the leaf and climbed up there.")
print("Soon it carried her safely to dry ground.")
print("Just at the time, a hunter nearby was throwing out his net")
print("towards the dove, hoping to trap it.")
print("Guessing what he was about to do,")
print("the ant quickly bit him on the heel.")
print("Felling the pain, the hunter dropped his net.")
print("the dove was quick to fly away to safety.")
print()
print("One good turn deserves another.")
