#am gonna print my Goal oriented academy classmates (who i sended in discord) in group 62

print("those who accepted")
print("deme tsintsadze")
print("ბარბარე წივილაშვილი")
print("those who i sended too but didnt seen it yet")
print("Mariam Xuxia")
print("Giorgi gerliani")
print("irma surnaridze")
print("sandro.bedoidze")
print("მარიამ ქელბაქიანი")
print("ნინო ტალახაძე")
print("გეგა დოლიძე")
print("დემე მაისურაძე")
print("გიორგი ბარამიძე")
print("thats all from group 62")
print()
print("now others who i friended")
print("lukaroinishvili_")
print("sandora111")